version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celeste_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # mapea al host para que puedas usar localhost desde tu máquina

volumes:
  db_data:
